//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clip
    {
        public int ID { get; set; }
        public int MediaID { get; set; }
        public string ClipName { get; set; }
        public string ThumbnailFile { get; set; }
        public int StartPosition { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FullMediaName { get; set; }
    
        public virtual VideoFile VideoFile { get; set; }
    }
}
